### ISSUE TITLE
home icon is hidden by toggle menu icon in cell phone mode

### ISSUE THREAD

**Issue by JoshuaVSherman** [IntegratedControls/LibraryFrontEnd#146]
![image](https://cloud.githubusercontent.com/assets/13340120/24205405/b5107608-0ef1-11e7-9895-1105e816eda5.png)

this is in app.html line 21
![image](https://cloud.githubusercontent.com/assets/13340120/24205468/dd239c88-0ef1-11e7-9b04-b979fe0d8981.png)

**Comment by JoshuaVSherman** [comment]
@joshstoro 
Hey Josh, would you please change your GitHub icon to make it easier for me to identify you when i'm working on the kanban board. Thanks

**Comment by JoshuaVSherman** [comment]
@ort2411 
here is the solution:
![image](https://cloud.githubusercontent.com/assets/13340120/24334957/363e204c-1242-11e7-9781-16c6910b287d.png)

**Comment by ort2411** [comment]
created new style 
div#drawer.style-scope.paper-drawer-panel.iron-selected {
  z-index: 2147483647;
}
